---
# tasks file for pip package manager

- name: Check if pip is already installed.
  command: "{{ pip_exec }} --version"
  ignore_errors: true
  changed_when: false
  check_mode: no
  register: pip_is_installed

- name: Install Pip if not present.
  package:
    name: "{{ pip_package }}"
    state: present
  register: pip_is_installed
  when: pip_is_installed.rc != 0

- name: Upgrade pip
  command: "{{ pip_exec }} install --upgrade pip"
  state: present

- name: Ensure packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_exec }}"
  with_items: "{{ packages }}"

